server {
    server_name arghyadip.store www.arghyadip.store 162.222.204.31;

    root /var/www/cinex/cineX_Frontend/dist;
    index index.html;

    # Backend API Endpoints — Direct reverse proxy to Spring Boot container/port
    location ~ ^/(auth|admin|vendor|movies|shows|bookings|payments|actuator) {
        proxy_pass http://localhost:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend SPA Router & Static Assets
    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/arghyadip.store/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/arghyadip.store/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = arghyadip.store) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name arghyadip.store www.arghyadip.store 162.222.204.31;
    return 301 https://$host$request_uri;
}
