# Development Profile Configurations
spring.datasource.url=jdbc:postgresql://localhost:5433/cinexdb?TimeZone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=cinex
spring.datasource.password=cinex123
spring.datasource.hikari.data-source-properties.TimeZone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arghyadippaul09100@gmail.com
spring.mail.password=hyhphkzspojzqfqo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Invitation App / Setup config
cinex.mail.from=noreply@cinex.com
cinex.mail.sender-name=CineX No-Reply
cinex.app.portal-url=http://localhost:5173/login
cinex.jwt.secret=cinex-super-secret-key-must-be-32-chars!!

# Actuator & Prometheus Configuration for development
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.defaults.metrics.export.enabled=true
management.prometheus.metrics.export.enabled=true
