spring.application.name=cinex
spring.datasource.url=jdbc:postgresql://localhost:5433/cinexdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=cinex
spring.datasource.password=cinex123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.h2.console.enabled=false
server.port=9000